apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example
  description: example.com
  annotations:
    sonarqube.org/project-key: value
spec:
  type: website
  lifecycle: production
  owner: user:guest
