apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: SonarQube
  description: Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    sonarqube.org/project-key: app
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
